name: Azure Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Navigate to tic-tac-toe (Angular application)
        run: cd tic-tac-toe

      - name: Where are we?
        run: ls

      - name: Install dependencies
        run: npm install

      - name: Build Angular Package
        run: npm run build
