name: Azure Deployment

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: play-tic-tac-toe
  AZURE_WEBAPP_PACKAGE_PATH: "."

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Build Angular Package
        run: |
          cd tic-tac-toe
          npm install
          npm run build

      - name: upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: server

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: artifact

      - name: "deploy to azure web app"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
